<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="13" passed="10" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-10T17:09:36 EEST" name="Default suite" finished-at="2022-04-10T17:11:53 EEST" duration-ms="136831">
    <groups>
    </groups>
    <test started-at="2022-04-10T17:09:36 EEST" name="Default test" finished-at="2022-04-10T17:11:53 EEST" duration-ms="136831">
      <class name="automation.NewTest">
        <test-method signature="alreadyaccount()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:09:36 EEST" name="alreadyaccount" finished-at="2022-04-10T17:09:43 EEST" duration-ms="7707" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alreadyaccount -->
        <test-method signature="footerLegalagreements()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:09:43 EEST" name="footerLegalagreements" finished-at="2022-04-10T17:09:52 EEST" duration-ms="8612" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://politrip.com/legal-agreements/service-assurance-agreement] but found [https://politrip.com/account/sign-up]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://politrip.com/legal-agreements/service-assurance-agreement] but found [https://politrip.com/account/sign-up]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at automation.NewTest.footerLegalagreements(NewTest.java:383)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- footerLegalagreements -->
        <test-method signature="footerlogo1()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:09:52 EEST" name="footerlogo1" finished-at="2022-04-10T17:10:00 EEST" duration-ms="7961" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://european-union.europa.eu/index_ro] but found [https://politrip.com/account/sign-up]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://european-union.europa.eu/index_ro] but found [https://politrip.com/account/sign-up]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at automation.NewTest.footerlogo1(NewTest.java:410)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- footerlogo1 -->
        <test-method signature="headerbuttonhome()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:10:00 EEST" name="headerbuttonhome" finished-at="2022-04-10T17:10:13 EEST" duration-ms="12992" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- headerbuttonhome -->
        <test-method signature="headerbuttonhowitworks()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:10:13 EEST" name="headerbuttonhowitworks" finished-at="2022-04-10T17:10:25 EEST" duration-ms="12003" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- headerbuttonhowitworks -->
        <test-method signature="headerbuttonlogin()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:10:25 EEST" name="headerbuttonlogin" finished-at="2022-04-10T17:10:35 EEST" duration-ms="10166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- headerbuttonlogin -->
        <test-method signature="headerbuttonsignup()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:10:35 EEST" name="headerbuttonsignup" finished-at="2022-04-10T17:10:45 EEST" duration-ms="10210" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- headerbuttonsignup -->
        <test-method signature="logo()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:10:45 EEST" name="logo" finished-at="2022-04-10T17:10:59 EEST" duration-ms="13528" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logo -->
        <test-method signature="signup0()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:10:59 EEST" name="signup0" finished-at="2022-04-10T17:11:13 EEST" duration-ms="14438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signup0 -->
        <test-method signature="signup1()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:11:13 EEST" name="signup1" finished-at="2022-04-10T17:11:21 EEST" duration-ms="7955" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signup1 -->
        <test-method signature="signup2()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:11:21 EEST" name="signup2" finished-at="2022-04-10T17:11:37 EEST" duration-ms="15229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signup2 -->
        <test-method signature="signup3()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:11:37 EEST" name="signup3" finished-at="2022-04-10T17:11:44 EEST" duration-ms="7317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signup3 -->
        <test-method signature="signup4()[pri:0, instance:automation.NewTest@5fbdfdcf]" started-at="2022-04-10T17:11:44 EEST" name="signup4" finished-at="2022-04-10T17:11:53 EEST" duration-ms="8610" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://politrip.com/account/sign-up/type-select] but found [https://politrip.com/account/sign-up]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://politrip.com/account/sign-up/type-select] but found [https://politrip.com/account/sign-up]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at automation.NewTest.signup4(NewTest.java:280)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signup4 -->
      </class> <!-- automation.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
